spring:
  quartz:
    job-store-type: memory # 默认为内存 memory 的方式
    wait-for-jobs-to-complete-on-shutdown: true # 关闭时等待任务完成
    overwrite-existing-jobs: true # 可以覆盖已有的任务
    properties: # quartz原生配置
      org:
        quartz:
          scheduler:
            instanceName: scheduler # 调度器实例名称
            instanceId: AUTO
          # JobStore 相关配置
          jobStore:
            class: org.quartz.simpl.RAMJobStore # JobStore 实现类
          # 线程池相关配置
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 指定线程池实现类，对调度器提供固定大小的线程池
    schedules:
      job-ref: myJob
      cron: 0/1 * * * * ?
